config/routes.rb
Rails.application.routes.draw do
  resource :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#home"
  get "privacy_policy", to: 'pages#privacy_policy'
  get "account_deletion", to: 'pages#account_deletion'
  get "tutorial", to: 'pages#tutorial'
  scope :api, defaults: { } do
    devise_for :users,
             controllers: {
                 sessions: 'login/sessions',
                 registrations: 'login/registrations'
             }
    # devise_for :users, controllers: { sessions: :sessions },
    #                    path_names: { sign_in: :login }



    # characters
    resource :characters
    get "characters", to: 'characters#index'
    get "characters/:id", to: 'characters#show'
    post "characters", to: 'characters#create'
    put "characters/:id", to: 'characters#update'
    delete "characters/:id", to: 'characters#destroy'
    post "characters/:id/items", to: 'characters#add_items'
    get "characters/:id/drops", to: 'characters#show_drops'
    post "characters/discord_create" => "characters#discord_create"

    # data
    get "datafile", to: 'data#datafile'

    # friends
    get "friendlist", to: 'friends#index'
    post "friendlist", to: 'friends#create'
    delete "friendlist/:id", to: 'friends#destroy'

    #teams
    get "teams", to: 'teams#index'
    get "teams/discord_create", to: 'teams#discord_create'
    get "teams/:id", to: 'teams#show'
    post "teams", to: 'teams#create'
    put "teams/:id", to: 'teams#update'
    delete "teams/:id", to: 'teams#destroy'
    post "teams/:id/characters", to: 'teams#add_characters'
    post "teams/:invite_code/invite", to: 'teams#invite'
    delete "teams/:id/characters", to: 'teams#remove_characters'

    #runs 
    get "/teams/:team_id/runs", to: 'runs#index'
    get "/teams/:team_id/runs/:id", to: 'runs#show'
    post "/teams/:team_id/runs", to: 'runs#create'
    get "/teams/:team_id/runs/:id/summary", to: 'runs#summary'
    post "/teams/:team_id/runs/:id/mark_completed", to: 'runs#mark_completed'
    get "/teams/:team_id/completed", to: 'runs#completed_index'

    #battles
    post "battles", to: 'battles#create'
    get "battles/:id", to: 'battles#show'
    post "battles/:id/create_drop", to: 'battles#create_drop'

    #raids
    get "raids/:id/items", to: 'raids#items'
    get "raids", to: 'raids#index'

    #drops
    get "/battles/:battle_id/drops/:id", to: 'drops#show'
    post "/battles/:battle_id/drops", to: 'drops#create'
    post "/battles/:battle_id/drops/:id", to: 'drops#update'

    #buffs
    get "buffs", to: 'data#buffs'

    delete "users/:id", to: 'users#delete'
    post "users/battletag", to: 'users#battletag'

    devise_scope :user do
      post "users/uuid", to: "login/sessions#uuid"
    end
  end
  get "oauth2/login", to: 'oauth#login'
  get "oauth2/callback", to: 'oauth#callback'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/account_deletion.html.erb
<div style="margin: 4em">
  <h1> To request account deletion, please email us at: <a href="mailto:info@raidcraft-app.com">info@raidcraft-app.com</a> </h1>
</div>

app/views/pages/home.html.erb
<html>
  <head>
 </head>
  <body class="active_admin logged_out new">
    <div class="center">

      <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %>">
                  <%= value %>
            </div>
      <% end %>
      
     <div><%= link_to "Test Oauth Login", oauth2_login_path %>
      <br>
      <%= link_to "Admin Login", new_admin_user_session_path %>

      <div>
        <a href="mailto:info@raidcraft-app.com">Contact Us</a>
      </div>
        
    </div>
  </body>
</html>

app/views/pages/privacy_policy.html.erb
<div style="margin: 4em">
  <h1 class="h1">Privacy Policy</h1>
  <h2>Information that is gathered from visitors</h2>
  <p>In common with other websites, log files are stored on the web server saving details such as the visitor's IP address, browser type, referring page and time of visit.</p>
  <p>Cookies may be used to remember visitor preferences when interacting with the website.</p>
  <p>Where registration is required, the visitor's email and a username will be stored on the server.</p>
  <h2>How the Information is used</h2>
  <p>The information is used to enhance the vistor's experience when using the website to display personalised content and possibly advertising.</p>
  <p>E-mail addresses will not be sold, rented or leased to 3rd parties.</p>
  <h2>Visitor Options</h2>
  <p>You may be able to block cookies via your browser settings but this may prevent you from access to certain features of the website.</p>
  <h2>Cookies</h2>
  <p>Cookies are small digital signature files that are stored by your web browser that allow your preferences to be recorded when visiting the website. Also they may be used to track your return visits to the website.</p>
  <p>3rd party advertising companies may also use cookies for tracking purposes.</p>
  <h2>Google Ads</h2>
  <p>Google, as a third party vendor, uses cookies to serve ads.</p>
  <p>Google's use of the DART cookie enables it to serve ads to visitors based on their visit to sites they visit on the Internet.</p>
  <p>Website visitors may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>
</div>

app/views/pages/tutorial.html.erb
<style>
  h1 {
    font-size: 2em;
    color: #333;
  }

  h2 {
    font-size: 1.5em;
    color: #333;
  }

  p {
    font-size: 1em;
    color: #333;
  }

  code {
    font-size: 1em;
    background-color: #eee;
    display:block;
    width: 600px;
  }
</style>
<div style="margin-left:2em">
  <h1>Discord Tutorial</h1>

  <h2>For Team Leads</h2>

  <p>As a team lead, you have the ability to create and manage teams. First, go to https://www.raidcraft-app.com/ to create a new account.</p>


  <p>Use the command "@Raidcraft-bot newrun" with your battle ID to initiate a new run for all players. Players can respond to the message with any emoji to participate</p>

  <p>Example:</p><p>

  You: <code>@Raidcraft-bot newrun NiceBest#1557</code></p><p>

  Raidcraft-Bot: <code>Let's raid with Raidcraft! React to this message to join the run</code>

  <p>The bot will send a private message to each participating player with instructions to create a character.</p>

  <h2>For Players</h2>

  <p>As a player, you can join a team and participate in runs. Creating an account at raidcraft-app.com is optional.</p>

  <p>Reply to a newrun request with an emoji to participate in the run. The bot will send you a private message with instructions to create a character.</p>  

 <p> Raidcraft-Bot: <code>NiceBest#1557 is starting a new run. If you already have an account on raidcraft-app.com, just reply with your battle ID to get your characters. Otherwise, let's create a new character. Reply to this message with your character's name.</code>
</p>
</div>